"""
utils/campaign_model.py
BrandSphere AI — Campaign KPI Prediction + Analytics
"""

import numpy as np
import pandas as pd
import os
import joblib


PLATFORM_MAP  = {"Instagram": 0, "Facebook": 1, "Twitter/X": 2}
INDUSTRY_MAP  = {"Tech": 7, "Retail": 6, "Food & Beverage": 2, "Healthcare": 3,
                  "Finance": 1, "Fashion": 0, "Education": 4, "Real Estate": 5}
OBJECTIVE_MAP = {"brand_awareness": 0, "conversion": 1, "engagement": 2}
REGION_MAP    = {"Africa": 0, "Asia Pacific": 1, "Europe": 2, "Latin America": 3,
                  "Middle East": 4, "North America": 5}

# Benchmarks for gauge charts
BENCHMARKS = {
    "CTR (%)":            {"low": 1.0, "avg": 3.5, "high": 7.0},
    "ROI (%)":            {"low": 50,  "avg": 180, "high": 400},
    "Engagement Score":   {"low": 40,  "avg": 65,  "high": 85},
}


def predict_campaign_kpis(platform: str, industry: str, objective: str, region: str,
                           budget_usd: float, audience_size: int,
                           impressions: int = 50000, clicks: int = 1500) -> dict:
    """
    Predict CTR, ROI, and Engagement Score for a proposed campaign.
    Falls back to statistical estimates if models not found.
    """
    base_path = os.path.dirname(__file__)

    # Encode inputs
    features = np.array([[
        PLATFORM_MAP.get(platform, 0),
        INDUSTRY_MAP.get(industry, 0),
        OBJECTIVE_MAP.get(objective, 0),
        REGION_MAP.get(region, 0),
        min(budget_usd / 50000, 1.0),
        min(audience_size / 5_000_000, 1.0),
        min(impressions / 2_000_000, 1.0),
        min(clicks / 50_000, 1.0),
    ]])

    target_cols = ["ctr_percent", "roi_percent", "engagement_score"]
    labels      = ["CTR (%)", "ROI (%)", "Engagement Score"]
    results = {}

    for col, label in zip(target_cols, labels):
        model_path = os.path.join(base_path, f"campaign_{col}_model.pkl")
        if os.path.exists(model_path):
            model = joblib.load(model_path)
            pred  = float(model.predict(features)[0])
        else:
            # Statistical fallback based on industry/platform patterns
            base  = {"CTR (%)": 3.5, "ROI (%)": 180, "Engagement Score": 65}[label]
            noise = np.random.normal(0, base * 0.1)
            pred  = max(0, base + noise)

        results[label] = {
            "value":     round(pred, 2),
            "benchmark": BENCHMARKS[label],
            "rating":    _rate_kpi(label, pred),
        }

    return results


def _rate_kpi(label: str, value: float) -> str:
    """Rate a KPI value relative to benchmarks."""
    bench = BENCHMARKS.get(label, {})
    if not bench:
        return "N/A"
    if value >= bench["high"]:   return "🟢 Excellent"
    elif value >= bench["avg"]:  return "🟡 Above Average"
    elif value >= bench["low"]:  return "🟠 Average"
    else:                        return "🔴 Below Average"


def get_regional_insights() -> pd.DataFrame:
    """Return regional campaign performance data for map visualization."""
    np.random.seed(42)
    regions = {
        "North America":  {"lat": 40.0,  "lon": -100.0, "ctr_avg": 4.2, "roi_avg": 210, "eng_avg": 72},
        "Europe":         {"lat": 50.0,  "lon":   15.0,  "ctr_avg": 3.8, "roi_avg": 185, "eng_avg": 68},
        "Asia Pacific":   {"lat": 20.0,  "lon":  100.0,  "ctr_avg": 3.5, "roi_avg": 170, "eng_avg": 65},
        "Latin America":  {"lat": -10.0, "lon":  -60.0,  "ctr_avg": 3.1, "roi_avg": 150, "eng_avg": 60},
        "Middle East":    {"lat": 25.0,  "lon":   50.0,  "ctr_avg": 2.9, "roi_avg": 140, "eng_avg": 58},
        "Africa":         {"lat":  0.0,  "lon":   20.0,  "ctr_avg": 2.5, "roi_avg": 120, "eng_avg": 54},
    }
    rows = []
    for region, data in regions.items():
        rows.append({
            "region":      region,
            "lat":         data["lat"],
            "lon":         data["lon"],
            "avg_ctr":     round(data["ctr_avg"] + np.random.normal(0, 0.3), 2),
            "avg_roi":     round(data["roi_avg"] + np.random.normal(0, 15), 1),
            "avg_engagement": round(data["eng_avg"] + np.random.normal(0, 3), 1),
        })
    return pd.DataFrame(rows)


def generate_campaign_package(company: str, taglines: list, campaign_content: dict,
                                kpi_results: dict, translations: dict, palette: list) -> bytes:
    """Package all campaign assets into a ZIP file and return bytes."""
    import zipfile, io, json

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # README
        readme = f"""BrandSphere AI — Campaign Kit for {company}
Generated by BrandSphere AI

Contents:
- taglines.txt       : Brand taglines (5 variants)
- campaign.txt       : Social media captions and hashtags
- translations.json  : Multilingual taglines
- color_palette.json : Brand color palette
- kpi_predictions.json: Campaign performance predictions
- brand_kit_README.txt: This file
"""
        zf.writestr("brand_kit_README.txt", readme)

        # Taglines
        taglines_text = "\n".join([f"{i+1}. {t}" for i, t in enumerate(taglines)])
        zf.writestr("taglines.txt", taglines_text)

        # Campaign content
        campaign_text = f"""SOCIAL MEDIA CAMPAIGN
Platform: {campaign_content.get('platform', 'Multi-platform')}

CAPTION:
{campaign_content.get('caption', '')}

HASHTAGS:
{' '.join(['#' + h.strip('#') for h in campaign_content.get('hashtags', [])])}

CALL TO ACTION:
{campaign_content.get('cta', '')}

REGIONAL STRATEGY:
{campaign_content.get('regional_strategy', '')}

BEST POSTING TIME:
{campaign_content.get('posting_time', '')}
"""
        zf.writestr("campaign.txt", campaign_text)

        # JSON files
        zf.writestr("translations.json",     json.dumps(translations, indent=2, ensure_ascii=False))
        zf.writestr("kpi_predictions.json",  json.dumps(kpi_results, indent=2))
        zf.writestr("color_palette.json",    json.dumps(palette, indent=2))

    zip_buffer.seek(0)
    return zip_buffer.read()
